version: '3'
services:
  blood-mysql:
    image: mysql:8.0.18
    ports:
      - "33085:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - ./blood-system-db:/var/lib/mysql
      - ./dbscripts:/docker-entrypoint-initdb.d
  eureka-service:
    image: eureka-app
    build: micro-services/eureka-discovery-server
    ports:
      - 8761:8761
  authentication-service:
    image: authentication-app
    build: micro-services/authentication-service
    ports:
      - 8082:8082
    depends_on:
      - blood-mysql
      - eureka-service
    links:
      - blood-mysql
      - eureka-service
  blood-service:
    image: blood-app
    build: micro-services/blood-bank
    ports:
      - 8084:8084
    depends_on:
      - blood-mysql
      - eureka-service
    links:
      - blood-mysql
      - eureka-service
 
  zuul-service:
    image: zuul-app
    build: micro-services/zuul-gateway
    ports:
      - 8083:8083
    depends_on:
      - blood-service
      - authentication-service
  angular-service:
    image: angular-app
    build: webapp/dist
    ports:
      - 4200:80
    depends_on:
      - blood-service
      - authentication-service
      - eureka-service
      - zuul-service
        
  
   