-- MySQL Script generated by MySQL Workbench
-- 11/05/19 16:00:00
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema blood_bank
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema blood_bank
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `blood_bank` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `blood_bank` ;

-- -----------------------------------------------------
-- Table `blood_bank`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `blood_bank`.`user` (
  `us_id` INT NOT NULL AUTO_INCREMENT,
  `us_username` VARCHAR(60) NOT NULL,
  `us_password` VARCHAR(60) NOT NULL,
  `us_firstname` VARCHAR(50) NOT NULL,
  `us_lastname` VARCHAR(50) NOT NULL,
  `us_age` INT NOT NULL,
  `us_gender` VARCHAR(10) NULL,
  `us_contact_no` BIGINT NOT NULL,
  `us_email` VARCHAR(50) NOT NULL,
  `us_weight` INT NOT NULL,
  `us_state` VARCHAR(50) NOT NULL,
  `us_area` VARCHAR(50) NOT NULL,
  `us_pin_code` INT NOT NULL,
  `us_blood_group` VARCHAR(10) NOT NULL,
  PRIMARY KEY (`us_id`))
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `blood_bank`.`role`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `blood_bank`.`role` (
  `ro_id` INT NOT NULL AUTO_INCREMENT,
  `ro_name` VARCHAR(10) NOT NULL,
  PRIMARY KEY (`ro_id`))
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `blood_bank`.`user_role`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `blood_bank`.`user_role` (
  `ur_id` INT NOT NULL AUTO_INCREMENT,
  `ur_us_id` INT NULL,
  `ur_ro_id` INT NULL,
  PRIMARY KEY (`ur_id`),
  INDEX `ur_us_fk_idx` (`ur_us_id` ASC),
  INDEX `ur_ro_fk_idx` (`ur_ro_id` ASC),
  CONSTRAINT `ur_us_fk`
    FOREIGN KEY (`ur_us_id`)
    REFERENCES `blood_bank`.`user` (`us_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `ur_ro_fk`
    FOREIGN KEY (`ur_ro_id`)
    REFERENCES `blood_bank`.`role` (`ro_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


CREATE TABLE IF NOT EXISTS `blood_bank`.`blood_requirement` (
  `br_id` INT NOT NULL AUTO_INCREMENT,
  `br_blood_group` VARCHAR(100) NOT NULL,
  `br_state` VARCHAR(100) NOT NULL,
  `br_area` VARCHAR(100) NOT NULL,
  `br_pincode` INT(6) NOT NULL,
  `br_contact_number` VARCHAR(10) NOT NULL,
  PRIMARY KEY (`br_id`))
ENGINE = InnoDB;

CREATE TABLE IF NOT EXISTS `blood_bank`.`blood_availability` (
  `ba_id` INT NOT NULL AUTO_INCREMENT,
  `ba_blood_group` VARCHAR(100) NULL,
  `ba_state` VARCHAR(100) NOT  NULL,
  `ba_area` VARCHAR(100) NOT NULL,
  `ba_pincode` INT(6) NOT NULL,
  `ba_contact_number` BIGINT NOT NULL,
  PRIMARY KEY (`ba_id`))
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `blood_bank`.`blood_donor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `blood_bank`.`blood_donor` (
  `bd_id` INT NOT NULL AUTO_INCREMENT,
  `bd_blood_group` VARCHAR(10) NOT NULL,
  `bd_state` VARCHAR(100) NOT NULL,
  `bd_area` VARCHAR(100) NOT NULL,
  `bd_pin_code` INT NOT NULL,
  `bd_contact_no` BIGINT NOT NULL,
 `bd_us_id` INT NOT NULL,
  PRIMARY KEY (`bd_id`),
  INDEX `bd_us_fk_idx` (`bd_us_id` ASC),
  CONSTRAINT `bd_us_fk`
    FOREIGN KEY (`bd_us_id`)
    REFERENCES `blood_bank`.`user` (`us_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `blood_bank`.`hospital`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `blood_bank`.`hospital` (
  `ho_id` INT NOT NULL AUTO_INCREMENT,
  `ho_hospital_name` VARCHAR(15) NOT NULL,
  `ho_city` VARCHAR(15) NOT NULL,
  PRIMARY KEY (`ho_id`))
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `blood_bank`.`slot`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `blood_bank`.`slot` (
  `sl_id` INT NOT NULL AUTO_INCREMENT,
  `sl_time` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`sl_id`))
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `blood_bank`.`slot_booking`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `blood_bank`.`slot_booking` (
  `sb_id` INT NOT NULL AUTO_INCREMENT,
  `sb_bd_id` INT NOT NULL,
  `sb_ho_id` INT NOT NULL,
  `sb_sl_id` INT NOT NULL,
  `sb_date` DATE NOT NULL,
  PRIMARY KEY (`sb_id`),
  INDEX `sb_bd_fk_idx` (`sb_bd_id` ASC),
  INDEX `sb_ho_fk_idx` (`sb_ho_id` ASC),
  INDEX `sb_sl_fk_idx` (`sb_sl_id` ASC),
  CONSTRAINT `sb_bd_fk`
    FOREIGN KEY (`sb_bd_id`)
    REFERENCES `blood_bank`.`blood_donor` (`bd_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `sb_ho_fk`
    FOREIGN KEY (`sb_ho_id`)
    REFERENCES `blood_bank`.`hospital` (`ho_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `sb_sl_fk`
    FOREIGN KEY (`sb_sl_id`)
    REFERENCES `blood_bank`.`slot` (`sl_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `blood_bank`.`user_experience`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `blood_bank`.`donor_experience` (
  `do_id` INT NOT NULL AUTO_INCREMENT,
  `do_ho_id` INT NOT NULL,
  `do_feedback_comments` VARCHAR(500) NOT NULL,
  PRIMARY KEY (`do_id`),
  INDEX `do_ho_fk_idx` (`do_ho_id` ASC),
  CONSTRAINT `do_ho_fk`
    FOREIGN KEY (`do_ho_id`)
    REFERENCES `blood_bank`.`hospital` (`ho_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `blood_bank`.`faq`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `blood_bank`.`faq` (
  `fa_id` INT NOT NULL AUTO_INCREMENT,
  `fa_us_id` INT NOT NULL,
  `fa_question` VARCHAR(100) NOT NULL,
  `fa_answer` VARCHAR(500) NULL,
  PRIMARY KEY (`fa_id`),
  INDEX `fa_us_fk_idx` (`fa_us_id` ASC),
  CONSTRAINT `fa_us_fk`
    FOREIGN KEY (`fa_us_id`)
    REFERENCES `blood_bank`.`user` (`us_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `blood_bank`.`user_notification`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `blood_bank`.`user_notification` (
  `un_id` INT NOT NULL AUTO_INCREMENT,
  `un_us_id` INT NOT NULL,
  `un_notification` VARCHAR(500) NOT NULL,
  `un_status` BOOLEAN DEFAULT FALSE,
  PRIMARY KEY (`un_id`),
  INDEX `un_us_fk_idx` (`un_us_id` ASC),
  CONSTRAINT `un_us_fk`
    FOREIGN KEY (`un_us_id`)
    REFERENCES `blood_bank`.`user` (`us_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;


-- -----------------------------------------------------
-- Insertion in Table `blood_bank`.`user`
-- -----------------------------------------------------
INSERT INTO `blood_bank`.`user` (`us_username`, `us_password`, `us_firstname`, `us_lastname`, `us_age`, 
	`us_gender`, `us_contact_no`, `us_email`, `us_weight`, `us_state`, `us_area`, `us_pin_code`, `us_blood_group`)
VALUES ("admin", "$2a$10$R/lZJuT9skteNmAku9Y7aeutxbOKstD5xE5bHOf74M2PHZipyt3yK", "Admin", "XYZ", 35, "Male", 9876543210, "admin.xyz@gmail.com", 50, "Maharashtra", "Pune", 411004, "O+"), 
	("user", "$2a$10$R/lZJuT9skteNmAku9Y7aeutxbOKstD5xE5bHOf74M2PHZipyt3yK", "John", "Doe", 35, "Male", 9876543210, "john.doe@gmail.com", 50, "Maharashtra", "Pune", 411004, "O+");
    
    -- -----------------------------------------------------
-- Insertion in Table `blood_bank`.`role`
-- -----------------------------------------------------
INSERT INTO `blood_bank`.`role` (`ro_name`)
VALUES ("ADMIN"),
       ("USER");

-- -----------------------------------------------------
-- Insertion in Table `blood_bank`.`user_role`
-- -----------------------------------------------------
INSERT INTO `blood_bank`.`user_role` (`ur_us_id`, `ur_ro_id`)
VALUES (1, 1),
       (2, 2);



INSERT INTO `blood_bank`.`blood_requirement`(`br_blood_group`,`br_state`,`br_area`,`br_pincode`,`br_contact_number`) VALUES("O+","Uttar Pradesh","Lucknow",226016,"1234567890");



INSERT INTO `blood_bank`.`blood_availability` (`ba_blood_group`, `ba_state`, `ba_area`, `ba_pincode`, `ba_contact_number`)
VALUES ("O+", "Himachal Pradesh", "Kullu", 867632, 8973647456),
       ("O-", "Rajasthan", "Jaipur", 867632, 8973647456),
       ("B-", "Rajasthan", "Jaipur", 867632, 8973647456),
       ("B+", "Himachal Pradesh", "Kullu", 867632, 8973647456),
       ("A+", "Rajasthan", "Kullu", 867632, 8973647456),
       ("A-", "Rajasthan", "Kullu", 867632, 8973647456),
       ("AB+", "Rajasthan", "Kullu", 867632, 8973647456),
       ("AB-", "Rajasthan", "Kullu", 867632, 8973647456);
	

-- -----------------------------------------------------
-- Insertion in Table `blood_bank`.`blood_donor`
-- -----------------------------------------------------
INSERT INTO `blood_bank`.`blood_donor` (`bd_blood_group`, `bd_state`, `bd_area`, `bd_pin_code`, `bd_contact_no`,bd_us_id)
VALUES ("O+", "Himachal Pradesh", "Kullu", 867632, 8973647456,2),
       ("O-", "Rajasthan", "Jaipur", 535322, 8973647456,2);
       
-- -----------------------------------------------------
-- Insertion in Table `blood_bank`.`hospital`
-- -----------------------------------------------------
INSERT INTO `blood_bank`.`hospital` (`ho_hospital_name`, `ho_city`)
VALUES ("Apollo Hospital", "Jaipur"),
       ("M G Hospital", "Delhi");
       
-- -----------------------------------------------------
-- Insertion in Table `blood_bank`.`slot`
-- -----------------------------------------------------
INSERT INTO `blood_bank`.`slot` (`sl_time`)
VALUES ("9 AM - 10 AM"),
	   ("10 AM - 11 AM"),
       ("11 AM - 12 PM"),
       ("12 PM - 1 PM"),
       ("1 PM - 2 PM"),
       ("2 PM - 3 PM"),
       ("3 PM - 4 PM"),
       ("4 PM - 5 PM"),
       ("5 PM - 6 PM");
       
-- -----------------------------------------------------
-- Insertion in Table `blood_bank`.`slot_booking`
-- -----------------------------------------------------
INSERT INTO `blood_bank`.`slot_booking` (`sb_bd_id`, `sb_ho_id`, `sb_sl_id`, `sb_date`)
VALUES (2, 1, 2, "2019-12-04");
       
-- -----------------------------------------------------
-- Insertion in Table `blood_bank`.`user_experience`
-- -----------------------------------------------------
INSERT INTO `blood_bank`.`donor_experience` (`do_ho_id`, `do_feedback_comments`)
VALUES (1, "Its a great experience of donating blood using this Portal."),
       (2, "Its a very user friendly Portal for Blood Bank");



-- -----------------------------------------------------
-- Insertion in Table `blood_bank`.`faq`
-- -----------------------------------------------------
INSERT INTO `blood_bank`.`faq` (`fa_us_id`, `fa_question`, `fa_answer`)
VALUES (1, "What is the minimum duration between 2 blood donations ?", null),
       (1, "How much unit of blood a person can donate at a time ?", null);
 INSERT INTO `blood_bank`.`faq` (`fa_us_id`, `fa_question`, `fa_answer`)
 VALUES(2, "How much unit of blood a person can donate at a time ?",null);
 INSERT INTO `blood_bank`.`faq` (`fa_us_id`, `fa_question`, `fa_answer`)
 VALUES(2, "How much unit of blood a person can donate at a time ?","1 Unit");
 
 
 select bd_id from user inner join blood_donor on user.us_id = blood_donor.bd_us_id  inner join slot_booking on blood_donor.bd_id = slot_booking.sb_bd_id where (us_username = ? and slot_booking.sb_date-CURDATE() > 90);
 
 select * from user;